table calculations
	lineageTag: e51c39d9-db10-451e-9645-5418f2df1e4c

	measure latency = AVERAGE(seller_weekly_fact[weekly_avg_delivery_delay])
		formatString: 0.00000
		displayFolder: _prerequisites_measures
		lineageTag: 07c73f1e-17d9-40a8-8dcc-d36277c73b65

	measure latency_previous_week =
			
			CALCULATE(
			    [latency],
			    DATEADD('calendar_dates'[Date], -7, DAY)
			)
		formatString: 0
		displayFolder: _prerequisites_measures
		lineageTag: 9de673f8-656a-4547-b52a-71d72122a335

	measure _DEBUG_previous_week =
			
			CALCULATE(
			    MAX('calendar_dates'[Date]),
			    DATEADD('calendar_dates'[Date], -7, DAY)
			)
		formatString: General Date
		displayFolder: _prerequisites_measures
		lineageTag: 1f738c60-8fd8-4eb2-afe9-c3c9a577ba37

	measure latency_current_week =
			
			VAR max_date = MAX(seller_weekly_fact[week_start_date])
			
			RETURN
			    CALCULATE([latency], calendar_dates[Date])
		formatString: 0
		displayFolder: _prerequisites_measures
		lineageTag: f232b501-3a69-473d-ab63-e4704129268a

	measure latency_4w_rolling_avg = ```
			
			AVERAGEX(
			    DATESINPERIOD('calendar_dates'[Date], 
			    LASTDATE('calendar_dates'[Date]), -28, DAY),
			    [latency]
			)
			```
		displayFolder: visual_measures
		lineageTag: 55c60c01-ab5e-4e92-8556-94460e9dd752

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tool_tip_week_start_date = SELECTEDVALUE(calendar_dates[Week Start Date])
		formatString: Short Date
		displayFolder: tooltips_measures
		lineageTag: 28178188-cfc3-48c6-a749-b8df1bdf8dd6

	measure total_order_volume = SUM(seller_weekly_fact[weekly_order_count])
		formatString: 0
		displayFolder: visual_measures
		lineageTag: 024606e7-3b5b-4ed9-a4b4-28c92ada3b6a

	measure is_new_seller =
			
			VAR first_order = SELECTEDVALUE(seller_dim[first_order_date])
			VAR current_date = MAX(calendar_dates[Date])
			
			RETURN
			    IF(
			        DATEDIFF(first_order, current_date, DAY) <= 30,
			        "Yes", "No"
			    )
		displayFolder: visual_measures
		lineageTag: bb1768b2-a5cb-4c01-ab6b-9598a5c58d39

	measure latency_slippage =
			
			VAR delta = [latency_current_week] - [latency_4w_rolling_avg]
			RETURN
			    IF([is_outlier] = 1, delta, BLANK())
		displayFolder: visual_measures
		lineageTag: 9d7e77f6-68af-4cfa-b461-cb1055c82c80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure is_outlier =
			
			VAR current_latency = [latency_current_week]
			VAR _4w_avg_latency = [latency_4w_rolling_avg]
			VAR current_year = SELECTEDVALUE(calendar_dates[Year])
			VAR is_valid_year = IF(current_year > 2022, TRUE(), FALSE())
			
			// Filter outliers to only show meaningful ones
			VAR slippage_delta = current_latency - _4w_avg_latency
			VAR is_meaningful = IF(slippage_delta > 0.5, 1, 0)
			
			// Standard deviation for current sellers across all weeks, except 2022 (incomplete date)
			VAR _stdev=
			    CALCULATE(
			        STDEVX.S(
			            seller_weekly_fact,
			            seller_weekly_fact[weekly_avg_delivery_delay]
			        ),
			        KEEPFILTERS(calendar_dates[Year] > 2022),
			        ALLEXCEPT(seller_weekly_fact, seller_weekly_fact[seller_id_int])
			    )
			
			// flag seller ("1") if current week is more than 1 std dev away from rolling mean (4w avg latency)
			VAR outlier_flags =
			    IF(
			        is_meaningful &&
			        is_valid_year &&
			        current_latency > (_4w_avg_latency + (1 * _stdev)),
			     1, 0
			     )
			
			RETURN
			    outlier_flags
		formatString: 0
		displayFolder: visual_measures
		lineageTag: 38c2f255-e5dc-451a-bdf1-3dbe0dfc897d

	measure seller_at_risk = ```
			
			COUNTROWS(
			    FILTER(
			        VALUES(seller_weekly_fact[seller_id_int]),
			        [is_outlier] = 1
			    )
			)
			
			```
		formatString: 0
		displayFolder: KPI_measures
		lineageTag: ff481b53-f15f-4f7b-92a8-8b8991868c2c

	measure revenue_exposed = ```
			
			VAR result = 
			SUMX(
			    VALUES(calendar_dates[Week Start Date]),
			    CALCULATE(
			        SUM(seller_weekly_fact[weekly_revenue]),
			        KEEPFILTERS(
			            FILTER(
			                VALUES(seller_weekly_fact[seller_id_int]),
			                [is_outlier] = 1 
			            )
			        )
			    )
			)
			VAR mask_blank = COALESCE(result, 0)
			
			RETURN
			    mask_blank
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: tooltips_measures
		lineageTag: 57b5b9af-aa8a-4551-8a57-8a49460b2ff8

	measure systemic_drift_pct =
			
			
			VAR _slipping_vol =
			    SUMX(
			        VALUES(calendar_dates[Week Start Date]),
			        CALCULATE(
			            [total_order_volume],
			            FILTER(VALUES(seller_weekly_fact[seller_id_int]), [latency_slippage] > 0)
			        )
			    )
			RETURN
			    DIVIDE(_slipping_vol, [total_order_volume], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI_measures
		lineageTag: 21bb73d1-b897-40e7-9eeb-9fb71f6a6ed1

	measure fulfillment_instability_index =
			
			
			VAR _4w_avg_latency = [latency_4w_rolling_avg]
			VAR _stddev =
			    CALCULATE(
			        STDEVX.S(seller_weekly_fact, seller_weekly_fact[weekly_avg_delivery_delay]),
			        KEEPFILTERS(calendar_dates[Year] > 2022)
			    )
			VAR result = DIVIDE(_stddev, ABS(_4w_avg_latency), 0 )
			RETURN
			    IF([seller_at_risk] > 0, result, BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI_measures
		lineageTag: 9412b079-f52a-4ddd-b355-3750b54a2281

	measure wrapper_is_outlier = IF([is_outlier], "Active", "No")
		displayFolder: visual_measures
		lineageTag: 2ec0bcb2-4c43-46e4-bdbb-7edcfa5cc443

	measure logistics_delay = ```
			
			VAR total_delay = [latency_current_week]
			VAR internal_lag = [internal_delay]
			VAR result = total_delay - [internal_delay]
			// VAR blank_mask = 
			//     IF(ISBLANK([seller_at_risk]), 0, result)
			// RETURN
			//     blank_mask
			
			RETURN
			    IF([seller_at_risk] > 0, result, BLANK())
			```
		displayFolder: visual_measures
		lineageTag: 41ecc5d8-3c35-433d-802c-c8e556044ff3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure internal_delay =
			
			VAR result = AVERAGE(seller_weekly_fact[weekly_avg_approval_lag])
			RETURN
			    IF([seller_at_risk] > 0, result, BLANK())
		displayFolder: visual_measures
		lineageTag: e1e72a03-c4d0-4765-9bb8-4e93fe8937e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure top_15_filter_color = ```
			
			VAR CurrentRank = 
			    RANKX(
			        ALLSELECTED('seller_dim'[seller_id_int]),
			        [latency_slippage],
			        ,
			        DESC,
			        Dense
			    )
			RETURN 
			    IF(CurrentRank <= 15, "#5C86A8", "#BBBBBE")
			```
		displayFolder: visual_measures
		lineageTag: 2349a8a2-63f6-4db4-8a46-231f5d4cc6c1

	measure is_outlier_global =
			
			CALCULATE(
			    [is_outlier],
			    ALLSELECTED(calendar_dates)
			)
		formatString: 0
		displayFolder: visual_measures
		lineageTag: c908f2d0-f3df-4583-9866-998dea86632d

	measure matrix_slippage_tracker = ```
			
			VAR global_flag = [is_outlier_global]
			VAR cell_slippage = [latency_current_week] - [latency_4w_rolling_avg]
			VAR result = 
			    IF(
			        global_flag = 1 &&
			        cell_slippage > 0,
			        cell_slippage,
			        BLANK()
			    )
			RETURN
			    result
			```
		displayFolder: visual_measures
		lineageTag: 1a56b5a8-3985-4adc-a97e-886801cddaf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

