table calculations
	lineageTag: ad26b367-a8d6-42af-8b25-fe1308ad1a37

	measure total_orders = SUM(product_weekly_fact[weekly_order_count])
		formatString: 0
		displayFolder: _prerequisites_measures
		lineageTag: 5f89224d-2c0f-40d5-9761-e65d9136294e

	measure avg_delivery_delay = AVERAGE(product_weekly_fact[weekly_avg_delivery_delay])
		displayFolder: _prerequisites_measures
		lineageTag: 4e142d1a-f1aa-401b-bc53-cca3a5b6bc0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure total_cancelled = SUM(product_weekly_fact[weekly_cancelled_orders])
		displayFolder: _prerequisites_measures
		lineageTag: fe57b795-2a34-4661-ab64-dc00dd293fa9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure total_revenue = SUM(product_weekly_fact[weekly_revenue])
		displayFolder: _prerequisites_measures
		lineageTag: ffefa665-dc81-4997-afe1-934e87c4646d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure avg_lead_time = AVERAGE(product_weekly_fact[weekly_avg_lead_time])
		displayFolder: _prerequisites_measures
		lineageTag: a3e4f028-c0da-4115-81b0-6cb2e215ad8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure lead_time_4w_rolling_avg = ```
			
			    AVERAGEX(
			        DATESINPERIOD('calendar_date'[Date], LASTDATE('calendar_date'[Date]), -28, DAY),
			        [avg_lead_time]
			    )
			```
		displayFolder: _prerequisites_measures
		lineageTag: ac5f3a7d-a595-4994-a5cc-423eef53d7d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure product_weight = ```
			
			LOOKUPVALUE(
			    product_dim[product_weight_g], 
			    product_dim[product_id_int], 
			    MAX(product_weekly_fact[product_id_int])
			)
			
			```
		displayFolder: visual_measures
		lineageTag: d800dd8c-ba8c-414b-a766-22e7a622834b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure product_volume_categ = ```
			
			LOOKUPVALUE(
			    product_dim[size_bucket], 
			    product_dim[product_id_int], 
			    MAX(product_weekly_fact[product_id_int])
			)
			```
		displayFolder: visual_measures
		lineageTag: 034dbb4d-401f-4f1c-86e3-9cc95b8a2fdf

	measure category_range_view = ```
			
			VAR highest_value =
			    MAXX(
			        ALL(product_dim[product_category_name]), 
			        [revenue_at_risk]
			    )
			
			VAR adjustment = highest_value * 1.05
			
			RETURN 
			    adjustment
			```
		displayFolder: visual_measures
		lineageTag: 70e2a94c-8098-4cbd-bb2b-fc2d01634053

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure is_outlier = ```
			
			
			VAR _slippage_threshold = [slippage_threshold Value]
			VAR _std_dev_boundary = [std_dev_boundary Value]
			
			VAR slippage_delta = [current_lead_time] - [lead_time_4w_rolling_avg]
			VAR is_meaningful = 
			    IF(
			        slippage_delta > _slippage_threshold, 
			        1, 0
			    )
			
			VAR _stddev =
			    CALCULATE(
			        STDEV.S(product_weekly_fact[weekly_avg_lead_time]),
			        ALLEXCEPT(product_weekly_fact, product_weekly_fact[product_id_int])
			    )
			
			VAR outlier_flags =
			    IF(
			        is_meaningful = 1 &&
			        [current_lead_time] > ([lead_time_4w_rolling_avg] + (_std_dev_boundary * _stddev)),
			        1, 0
			    )
			    
			RETURN
			    outlier_flags
			```
		formatString: 0
		displayFolder: _prerequisites_measures
		lineageTag: f8779455-7694-4bf2-ae1c-3b70bfb53cae

	measure current_lead_time = CALCULATE([avg_lead_time], calendar_date[Date])
		displayFolder: _prerequisites_measures
		lineageTag: 28f1c97e-1537-47c4-b5e5-f290312eda5a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure lead_time_slippage =
			
			VAR delta = [current_lead_time] - [lead_time_4w_rolling_avg]
			RETURN
			    IF([is_outlier] = 1, delta, BLANK())
		displayFolder: _prerequisites_measures
		lineageTag: 82b9fa97-dff1-4b5c-8a0c-64a01514fcbd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure product_at_risk =
			
			COUNTROWS(
				FILTER(
					VALUES(product_dim[product_id_int]),
					[is_outlier]=1
				)
			)
		formatString: 0
		displayFolder: KPI_measures
		lineageTag: 201fa0cd-af5b-4254-82a1-4e1cc60a22f8

	measure lead_time_volatility = ```
			
			VAR at_risk_products =
				FILTER(
					VALUES(product_dim[product_id_int]),
					[is_outlier]=1
				)
			VAR result = 
			    CALCULATE(
			        STDEV.S(product_weekly_fact[weekly_avg_lead_time]),
			        at_risk_products
			    )
			RETURN
			    result
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI_measures
		lineageTag: ce579d10-b2ce-4756-b616-e86f30ddba73

	measure revenue_at_risk =
			
			CALCULATE(
			    [total_revenue],
			    FILTER(
			        VALUES(product_dim[product_id_int]),
			        [is_outlier] = 1
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: KPI_measures
		lineageTag: 68fb4724-091d-41fc-bb40-e051143043f6

	measure chart_format_revenue_at_risk = ```
			
			    IF(
			        [revenue_at_risk] < 1000000,
			        FORMAT([revenue_at_risk], "#,##0, K"),
			        FORMAT([revenue_at_risk], "#,##0,, M")
			    )
			```
		displayFolder: visual_measures
		lineageTag: fc2ad2ba-cedc-43f5-a2ab-6be8495a2da7

	measure bubble_size_sensitivity = [revenue_at_risk] ^ 3.5
		displayFolder: visual_measures
		lineageTag: 9ac3920f-fd02-4dc6-8c06-be4b28cee937

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure last_source_update = MAX(source_last_update_time[Last_Update_Time])
		formatString: General Date
		displayFolder: visual_measures
		lineageTag: 5ec76ac2-a2c7-46c5-9662-62d3726df3b2

	measure tooltip_week_start_date = SELECTEDVALUE(calendar_date[Week Start Date])
		formatString: Short Date
		displayFolder: visual_measures_tooltip
		lineageTag: d2eaf8be-8d91-4540-9a22-b44c106083fa

	measure tooltip_product_id = SELECTEDVALUE(product_dim[product_id_int])
		formatString: 0
		displayFolder: visual_measures_tooltip
		lineageTag: 0a37d776-43f7-4156-8172-7df15421a48d

	measure format_product_id_count = ```
			
			VAR _distinct_count = [product_at_risk]
			VAR format_count = 
			    IF(_distinct_count < 1000,
			        FORMAT(_distinct_count, "0"),
			        FORMAT(_distinct_count, "#,000")
			    )
			RETURN
			    format_count
			```
		displayFolder: visual_measures
		lineageTag: f8b1832f-1d12-4f7c-b956-d5aaf0ed3e28

	measure format_total_orders = ```
			
			VAR order_at_risk =
			    CALCULATE(
			        [total_orders],
			        FILTER(
			            VALUES(product_dim[product_id_int]),
			            [is_outlier] = 1
			        )
			    )
			
			VAR _format = 
			    IF(
			        order_at_risk < 1000,
			        FORMAT(order_at_risk, "0"),
			        FORMAT(order_at_risk, "#,##0,.00 K")
			    )
			RETURN
			    _format
			```
		displayFolder: visual_measures
		lineageTag: 5a27ba7d-4894-4dda-af00-710494c49db4

	measure tooltip_format_revenue_at_risk = ```
			
			    IF(
			        [revenue_at_risk] < 1000000,
			        FORMAT([revenue_at_risk], "#,##0,.00 K"),
			        FORMAT([revenue_at_risk], "#,##0,,.00 M")
			    )
			```
		displayFolder: visual_measures_tooltip
		lineageTag: 487c13a3-d35f-4563-b2a4-3ac65e9579b5

	measure tooltip_oversize =
			
			COUNTROWS(
			    FILTER(
			        VALUES(product_dim),
			        product_dim[size_bucket] = "Oversize" && [is_outlier] = 1
			    )
			)
		formatString: 0
		displayFolder: visual_measures_tooltip
		lineageTag: c5d02df5-ef42-44ec-ab7e-c0075dfc2e00

	measure tooltip_heavy =
			
			COUNTROWS(
			    FILTER(
			        VALUES(product_dim),
			        product_dim[size_bucket] = "Heavy" && [is_outlier] = 1
			    )
			)
		formatString: 0
		displayFolder: visual_measures_tooltip
		lineageTag: 641a1226-1192-40a4-ae22-ca33f840a7b1

	measure tooltip_standard =
			
			COUNTROWS(
			    FILTER(
			        VALUES(product_dim),
			        product_dim[size_bucket] = "Standard" && [is_outlier] = 1
			    )
			)
		formatString: 0
		displayFolder: visual_measures_tooltip
		lineageTag: fd54c690-a1fa-4d44-9193-a6a3cdb1a028

	measure tooltip_small =
			
			COUNTROWS(
			    FILTER(
			        VALUES(product_dim),
			        product_dim[size_bucket] = "Small" && [is_outlier] = 1
			    )
			)
		formatString: 0
		displayFolder: visual_measures_tooltip
		lineageTag: 58b932ba-937d-4c51-a955-947f6ae14994

	measure item_rank = ```
			
			CALCULATE(
			    RANKX(
			        FILTER(
			            ALL(product_dim[product_id_int]),
			            [revenue_at_risk] > 0
			        ),                
			        [revenue_at_risk],
			        ,
			        DESC
			    )
			)
			```
		formatString: 0
		displayFolder: _paging_measures
		lineageTag: 30c6ee81-29ef-48da-9463-572a9d3eec88

	measure item_rank_filter = ```
			
			VAR _page = [paging_helper Value]
			VAR _page_size = [table_items Value]
			
			VAR item_rank = [item_rank]
			
			VAR _start = (_page - 1) * _page_size + 1
			VAR _end = _page * _page_size
			
			VAR is_in_range = 
			    IF(
			        item_rank >= _start && 
			        item_rank <= _end, 
			        1, 
			        0
			    )
			
			RETURN
			    is_in_range
			```
		formatString: 0
		displayFolder: _paging_measures
		lineageTag: a4903fad-285f-4ea3-81c0-4e0502076e79

	measure item_rank_string = CONCATENATE("#",[item_rank])
		displayFolder: _paging_measures
		lineageTag: 2bd6f813-81d9-40d3-b67e-8dd5bd0bbe75

	measure max_page =
			
			ROUNDUP(
			    DIVIDE(VALUE([product_at_risk]),  [table_items Value]),
			    0
			)
		displayFolder: _paging_measures
		lineageTag: eb2e2e69-5b90-495c-9f45-3d465ab363d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure page_filter = ```
			
			VAR _total_items = VALUE([product_at_risk])
			VAR items_per_page = [table_items Value]
			VAR max_page = 
			    ROUNDUP(
			        DIVIDE(_total_items, items_per_page),
			        0
			    )
			VAR _page_filter =
			    IF(
			        paging_helper[paging_helper Value] <= max_page,
			        1, 0
			    )
			RETURN
			    _page_filter
			```
		formatString: 0
		displayFolder: _paging_measures
		lineageTag: 03fe11bf-0886-4946-9653-075bdafb6b5e

	measure current_viewed_filter =
			
			VAR _is_at_risk = [product_at_risk]
			VAR _is_on_page = [item_rank_filter]
			
			RETURN
			IF(
			    _is_at_risk = 1 && _is_on_page = 1,
			    "#5C86A8",
			    "#999999"
			)
		displayFolder: _paging_measures
		lineageTag: 316a0377-b240-41ce-88af-8867465643ca

	measure color_format_revenue_at_risk = DIVIDE([revenue_at_risk], [total_revenue])
		displayFolder: visual_measures
		lineageTag: dc3c0f2d-76fb-4ed8-a5fc-9591ccae5782

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

